config/routes.rb
Rails.application.routes.draw do

  # get 'create', to: 'projects#creater_test' # Раскомментировать для создания списка задач
  get 'projects/', to: 'projects#index'
  post 'todos/', to: 'todos#create_task'
  get 'projects/:project_id/todos/:todo_id', to: 'projects#task_completed_check'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :todos
end

app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :project
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def index
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  def index
    @projects = Project.all
    render json: {projects: @projects}
  end

  def task_completed_check
    @project = Project.find(params[:project_id])
    return false unless @project
    @todo = @project.todos.find(params[:todo_id])
    return false unless @todo
    if(@todo.isCompleted == true)
      @todo.isCompleted = false
    else 
      @todo.isCompleted = true
    end
    @todo.save()
  end

  # def creater_test # Раскомментировать для создания списка задач
  #   @project = Project.create({title: 'семья'})
  #   @project.todos.create({text: 'Купить молоко', isCompleted: false})
  #   @project.todos.create({text: 'Заменить масло в двигателе до 23 апреля', isCompleted: false})
  #   @project.todos.create({text: 'Отправить письмо бабушке', isCompleted: true})
  #   @project.todos.create({text: 'Заплатить за квартиру', isCompleted: false})
  #   @project.todos.create({text: 'Забрать обувь из ремонта', isCompleted: false})
  #   @project.save()

  #   @project = Project.create({title: 'Работа'})
  #   @project.todos.create({text: 'Позвонить заказчику', isCompleted: true})
  #   @project.todos.create({text: 'Отправить документы', isCompleted: true})
  #   @project.todos.create({text: 'Заполнить отчет', isCompleted: false})
  #   @project.save()

  #   @project = Project.create({title: 'Прочее'})
  #   @project.todos.create({text: 'Позвонить другу', isCompleted: false})
  #   @project.todos.create({text: 'Подготовиться к поездке', isCompleted: false})
  #   @project.save()
  #   @project = Project.all
  #   render json: {projects: @project}
  # end


end

app/controllers/todos_controller.rb
class TodosController < ApplicationController

  def create_task(project_id=nil, text=nil, isCompleted=false) 
    render json: {projects: @projects};
    return false unless text;
    if !project_id
      if (Project.where(title: 'others...').count != 0)
        @project = Project.find_by(title: 'others...');
      else
        @project = Project.create(title:'othets...');
      end
    else
      @project = Project.find(project_id);
    end
    @project.todos.create({text: text, isCompleted: isCompleted});
    @project.save();
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tasklist</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :todos %>
    <%= form.text_field :todos %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Projects</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Todos</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.title %></td>
        <td><%= project.todos %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @project.title %>
</p>

<p>
  <strong>Todos:</strong>
  <%= @project.todos %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/todos/_form.html.erb
<%= form_with(model: todo) do |form| %>
  <% if todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
        <% todo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_field :text %>
  </div>

  <div class="field">
    <%= form.label :isCompleted %>
    <%= form.check_box :isCompleted %>
  </div>

  <div class="field">
    <%= form.label :project_id %>
    <%= form.text_field :project_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/todos/edit.html.erb
<h1>Editing Todo</h1>

<%= render 'form', todo: @todo %>

<%= link_to 'Show', @todo %> |
<%= link_to 'Back', todos_path %>

app/views/todos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Todos</h1>

<table>
  <thead>
    <tr>
      <th>Text</th>
      <th>Iscompleted</th>
      <th>Project</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todos.each do |todo| %>
      <tr>
        <td><%= todo.text %></td>
        <td><%= todo.isCompleted %></td>
        <td><%= todo.project_id %></td>
        <td><%= link_to 'Show', todo %></td>
        <td><%= link_to 'Edit', edit_todo_path(todo) %></td>
        <td><%= link_to 'Destroy', todo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Todo', new_todo_path %>

app/views/todos/new.html.erb
<h1>New Todo</h1>

<%= render 'form', todo: @todo %>

<%= link_to 'Back', todos_path %>

app/views/todos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @todo.text %>
</p>

<p>
  <strong>Iscompleted:</strong>
  <%= @todo.isCompleted %>
</p>

<p>
  <strong>Project:</strong>
  <%= @todo.project_id %>
</p>

<%= link_to 'Edit', edit_todo_path(@todo) %> |
<%= link_to 'Back', todos_path %>